// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS9PO9zCgcxX4GumNW4I7PM8QNY7eovJ8',
    appId: '1:983859430699:android:f92647f9e98846e571716e',
    messagingSenderId: '983859430699',
    projectId: 'viovid-e5899',
    storageBucket: 'viovid-e5899.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ukRV8kPMXQnLkqAzCNRCKuiPi6aRlGU',
    appId: '1:983859430699:ios:676eb9be06eb384e71716e',
    messagingSenderId: '983859430699',
    projectId: 'viovid-e5899',
    storageBucket: 'viovid-e5899.firebasestorage.app',
    iosBundleId: 'com.example.viovidApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlzeEp2V2qZFaUEnbfrsgiih58Yun4PUc',
    appId: '1:564614101400:web:444b9a3d0ff3a947e753ed',
    messagingSenderId: '564614101400',
    projectId: 'viovid-2',
    authDomain: 'viovid-2.firebaseapp.com',
    storageBucket: 'viovid-2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNXGsuPi8cUvSLh3UTK-ycwvWvc3o48lw',
    appId: '1:564614101400:ios:b9ab0eed94e82a55e753ed',
    messagingSenderId: '564614101400',
    projectId: 'viovid-2',
    storageBucket: 'viovid-2.firebasestorage.app',
    iosBundleId: 'com.example.viovidApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlzeEp2V2qZFaUEnbfrsgiih58Yun4PUc',
    appId: '1:564614101400:web:a35efda478751069e753ed',
    messagingSenderId: '564614101400',
    projectId: 'viovid-2',
    authDomain: 'viovid-2.firebaseapp.com',
    storageBucket: 'viovid-2.firebasestorage.app',
  );

}